---
- hosts: server
  remote_user: ubuntu
  become: yes
  tasks:
    # - name: Generate SSH Key Pair
    #   shell: ssh-keygen -t rsa -b 4096 -f /home/ec2-user/mykey
    #   args:
    #     executable: /bin/bash
    #   register: keygen_result
    # - name: Show Public Key
    #   debug:
    #     var: keygen_result.stdout
    - name: Install Docker
      apt:
        name:
          - docker
          - docker-compose
        state: present
    - name: Login DockerHub
      shell: docker login -u "{{DOCKER_USERNAME}}" -p "{{DOCKER_PASSWORD}}"
    - name: Copy file
      copy:
        src: docker-compose.yaml
        dest: /home/ubuntu/
    - name: Restart docker-compose
      shell: |
          docker-compose stop
          docker-compose rm -f
          docker-compose pull
          docker-compose up -d
...
  
